### ISSUE TITLE
Add vendor/ folder to .gitignore

### ISSUE THREAD

**Issue by kktsvetkov** [GBSEcom/PHP#3]
You do not need to keep `vendor` folder in the repo @ericmargules. It inflates the downloaded packagist package and it will never be used when installed via composer. Please add it to `.gitignore`

**Comment by ericmargules** [comment]
@kktsvetkov thanks for the tip. We'll get that taken care of for the next release.

**Comment by kktsvetkov** [comment]
@ericmargules you are planning on a release? A stable release? I am asking because right now we are using `dev` for the composer package, and that's going to change a lot more than a "release". I would feel more comfortable with a release

**Comment by ericmargules** [comment]
@kktsvetkov next release should be around September 21

**Comment by ericmargules** [comment]
Vender folder has been added to gitignore
