### ISSUE TITLE
Could not find a version of package first-data/gateway matching your minimum-stability 

### ISSUE THREAD

**Issue by eventhorizonpl** [GBSEcom/PHP#5]
Hi,

Can you please tag versions in your repo? I'll try to workaround that, but is your SDK is stable, you should use git tag feature...

Best regards,
Michal

composer.phar require first-data/gateway

  [InvalidArgumentException]
  Could not find a version of package first-data/gateway matching your minimum-stability (stable). Require it with an explicit version constraint allowing
   its desired stability.

**Comment by ericmargules** [comment]
Hi there @eventhorizonpl , this should be resolved for v1.8.0. Please let me know if it is. If I don't hear from you, I'll close the issue. Thanks!

**Comment by eventhorizonpl** [comment]
Hi,

Yes, this helped. Thank you very much.

Best regards,
Michal
