### ISSUE TITLE
400 - INVALID_INPUT

### ISSUE THREAD

**Issue by iseries** [GBSEcom/PHP#6]
Hello,

I'm trying to create a payment URL by calling `createPaymentUrl()` from `FirstData\FirstApi\Client\Api\PaymentURLApi`.
In my testing i got a 400 Response: "Invalid value for AuthorizationType". 

**What does that mean?** 
I can't find any information on this. Neither in the docs nor in the FirstData support pages. I have no starting point for debugging or further testing. Can someone give me some advice?

```
array(4) {
    ["clientRequestId"]=>
    string(36) "29ee036b-d8c3-4680-81e4-4e9ff161a1e4"
    ["apiTraceId"]=>
    string(27) "YK0UVYWvChhfuPciq2eWHAAAATw"
    ["responseType"]=>
    string(10) "BadRequest"
    ["error"]=>
    object(FirstData\FirstApi\Client\Model\Error)#1358 (1) {
      ["container":protected]=>
      array(3) {
        ["code"]=>
        string(13) "INVALID_INPUT"
        ["message"]=>
        string(37) "Invalid value for AuthorizationType: "
        ["details"]=>
        NULL
      }
    }
  }
```

Update: I tried with `FirstData\FirstApi\Client\Simple\PaymentURLApi` but the response is the same.

**Comment by ericmargules** [comment]
Hi, @iseries. Are you supplying the optional "Region" header? If so, can you try your request again without it?

**Comment by iseries** [comment]
Hi @ericmargules . Many Thanks! This solved my problem. To be honest, the error response was a bit confusing and misleading

**Comment by ericmargules** [comment]
@iseries I 100% agree. We'll see about cleaning that up and making it more transparent in the future. Thanks for raising the issue.
